version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo pip install mkdocs mkdocs-material pygments
      - run: ./.circleci/deploy.sh
